server:
  context-path: 
  port: 1111   # HTTP (Tomcat) port

spring:

   datasource:
      url:  jdbc:mysql://192.168.132.130:32768/test
      username:  root
      password:  210053 
      driverClassName : com.mysql.jdbc.Driver
      
   application:
     name: spring-boot-service 
     
eureka:
  instance:
    hostname: 127.0.0.1   #${host} 可以在maven编译时设置参数
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://192.168.132.130:8761/eureka/

     
     
     
   


